#driver_config:
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

driver:
  name: vagrant

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos6
    driver:
      box: "opscode-centos-6.6"
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
      network:
      - ["forwarded_port", {guest: 80, host: 8888}]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[mysecurity-cookbook::default]
    attributes:
