#driver_config:
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

driver:
  name: vagrant

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero
  # Download and install this exact version of chef-client
  require_chef_omnibus: 12.4.1
  # Use the local chef-client rpm specified in install_chef_rpm.sh: 
  chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :enabled

platforms:
  - name: centos5
    driver:
      box: 'chef/centos-5.11'
      network:
      - ['private_network', {ip: '192.168.56.42'}]
      # Mount local /Users/apop/chef-kits folder as /mnt/share on the VM 
      synced_folders:
      - ['~/chef-kits', '/mnt/share', 'disabled: false']
      customize:
        cpus: 1
        memory: 1024
  - name: centos6
    driver:
      #gui: true
      box: 'opscode-centos-6.6'
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ['private_network', {ip: '192.168.56.41'}]
      # Mount local /Users/apop/chef-kits folder as /mnt/share on the VM
      synced_folders:
      - ['/Users/apop/chef-kits', '/mnt/share', 'disabled: false']
      customize:
        cpus: 1
        memory: 1024

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[mysecurity-cookbook::default]
      - recipe[stig::default]
      - recipe[audit-cis::centos6-110]
    attributes:
